"""workout_isdeleted_to_boolean

Revision ID: 0bfd9556fbbe
Revises: d0de9ed7381e
Create Date: 2024-07-28 16:26:40.301751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bfd9556fbbe'
down_revision: Union[str, None] = 'd0de9ed7381e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('workout', 'is_deleted',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    op.execute("ALTER TABLE workout ALTER COLUMN is_deleted TYPE BOOLEAN USING is_deleted::BOOLEAN")
    # op.alter_column('workout_day', 'is_deleted',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    op.execute("ALTER TABLE workout_day ALTER COLUMN is_deleted TYPE BOOLEAN USING is_deleted::BOOLEAN")
    # op.alter_column('workout_day_exercise', 'is_deleted',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    op.execute("ALTER TABLE workout_day_exercise ALTER COLUMN is_deleted TYPE BOOLEAN USING is_deleted::BOOLEAN")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workout_day_exercise', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('workout_day', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('workout', 'is_deleted',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
