"""member Coach and enum change

Revision ID: 117bc4d0bda5
Revises: 1e183eb827e7
Create Date: 2024-08-28 13:32:27.013488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '117bc4d0bda5'
down_revision: Union[str, None] = '1e183eb827e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'phone',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_column('client', 'own_member_id')
    op.drop_column('client', 'client_since')
    op.drop_column('client', 'activated_on')
    op.drop_column('client', 'check_in')
    op.add_column('client_organization', sa.Column('own_member_id', sa.String(), nullable=True))
    op.add_column('client_organization', sa.Column('activated_on', sa.Date(), nullable=True))
    op.add_column('client_organization', sa.Column('check_in', sa.DateTime(), nullable=True))
    op.alter_column('coach', 'phone',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('coach', 'mobile_number',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_column('coach', 'own_coach_id')
    op.drop_column('coach', 'coach_since')
    op.drop_column('coach', 'check_in')
    op.add_column('coach_organization', sa.Column('check_in', sa.DateTime(), nullable=True))
    op.add_column('coach_organization', sa.Column('own_coach_id', sa.String(), nullable=True))
    op.alter_column('staff', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('staff', 'mobile_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'mobile_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('staff', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_column('coach_organization', 'own_coach_id')
    op.drop_column('coach_organization', 'check_in')
    op.add_column('coach', sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('coach', sa.Column('coach_since', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('coach', sa.Column('own_coach_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('coach', 'mobile_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.alter_column('coach', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    op.drop_column('client_organization', 'check_in')
    op.drop_column('client_organization', 'activated_on')
    op.drop_column('client_organization', 'own_member_id')
    op.add_column('client', sa.Column('check_in', postgresql.TIMESTAMP(precision=6), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('activated_on', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('client_since', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('own_member_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('client', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)
    # ### end Alembic commands ###
