"""exercise table changes

Revision ID: 1981c2d283ba
Revises: c876a37af894
Create Date: 2024-07-30 11:07:15.076382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1981c2d283ba'
down_revision: Union[str, None] = 'c876a37af894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    difficulty_enum = sa.Enum('Novice', 'Beginner', 'Intermediate', 'Advance', 'Expert', name='difficulty')
    difficulty_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('exercise', sa.Column('org_id', sa.Integer(), nullable=True))
    op.add_column('exercise', sa.Column('difficulty',difficulty_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'difficulty')
    op.drop_column('exercise', 'org_id')
    # ### end Alembic commands ###
