"""ClientMembershipPlan table changes

Revision ID: 68891312562b
Revises: b1b27318989f
Create Date: 2024-08-15 11:35:06.554313

"""
from typing import Sequence, Union
import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68891312562b'
down_revision: Union[str, None] = 'b1b27318989f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_coach', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('client_coach', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('client_membership', sa.Column('auto_renewal', sa.Boolean(), nullable=True))
    op.add_column('client_organization', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('client_organization', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_organization', 'updated_at')
    op.drop_column('client_organization', 'created_at')
    op.drop_column('client_membership', 'auto_renewal')
    op.drop_column('client_coach', 'updated_at')
    op.drop_column('client_coach', 'created_at')
    # ### end Alembic commands ###
