"""added columns in meal plan and foods

Revision ID: b1b27318989f
Revises: 7a9da3441dd4
Create Date: 2024-08-13 17:25:14.838718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1b27318989f'
down_revision: Union[str, None] = '7a9da3441dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

food_visible_for_enum = postgresql.ENUM('only_me', 'members', 'coaches_and_staff', 'everyone', name='foodvisiblefor', create_type=False)

def upgrade() -> None:
    food_visible_for_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exercise_equipment_exercise_id'), 'exercise_equipment', ['exercise_id'], unique=False)
    op.add_column('foods', sa.Column('img_url', sa.String(), nullable=True))
    op.add_column('foods', sa.Column('visible_for',food_visible_for_enum, nullable=True))
    op.add_column('meal_plan', sa.Column('carbs', sa.Float(), nullable=True))
    op.add_column('meal_plan', sa.Column('fats', sa.Float(), nullable=True))
    op.add_column('meal_plan', sa.Column('protein', sa.Float(), nullable=True))
    op.alter_column('workout_day', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'day_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('workout_day', 'week',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day', 'day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_workout_day_workout_id'), 'workout_day', ['workout_id'], unique=False)
    op.alter_column('workout_day_exercise', 'workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('workout_day_exercise', 'exercise_type',
               existing_type=postgresql.ENUM('time_based', 'repetition_based', name='exercisetype'),
               nullable=False)
    op.alter_column('workout_day_exercise', 'sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_workout_day_exercise_exercise_id'), 'workout_day_exercise', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_day_exercise_workout_day_id'), 'workout_day_exercise', ['workout_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_day_exercise_workout_day_id'), table_name='workout_day_exercise')
    op.drop_index(op.f('ix_workout_day_exercise_exercise_id'), table_name='workout_day_exercise')
    op.alter_column('workout_day_exercise', 'sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'exercise_type',
               existing_type=postgresql.ENUM('time_based', 'repetition_based', name='exercisetype'),
               nullable=True)
    op.alter_column('workout_day_exercise', 'exercise_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day_exercise', 'workout_day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_workout_day_workout_id'), table_name='workout_day')
    op.alter_column('workout_day', 'day',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'week',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('workout_day', 'day_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('workout_day', 'workout_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('meal_plan', 'protein')
    op.drop_column('meal_plan', 'fats')
    op.drop_column('meal_plan', 'carbs')
    op.drop_column('foods', 'visible_for')
    op.drop_column('foods', 'img_url')
    op.drop_index(op.f('ix_exercise_equipment_exercise_id'), table_name='exercise_equipment')
    # ### end Alembic commands ###
