"""Client changes settings

Revision ID: d7b327ea1931
Revises: f1c22f76115d
Create Date: 2024-07-02 17:23:05.091280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7b327ea1931'
down_revision: Union[str, None] = 'f1c22f76115d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('org_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'org_id')
    # ### end Alembic commands ###
