"""Updated staff attr

Revision ID: f60c0daa7703
Revises: d7b327ea1931
Create Date: 2024-07-02 18:37:01.101936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60c0daa7703'
down_revision: Union[str, None] = 'd7b327ea1931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.add_column('staff', sa.Column('own_staff_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'own_staff_id')
    op.drop_column('permission', 'resource_id')
    # ### end Alembic commands ###
