"""updated optional fields in exercise

Revision ID: fc667d552c48
Revises: 6a968b2da37b
Create Date: 2024-08-21 13:19:18.405933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc667d552c48'
down_revision: Union[str, None] = '6a968b2da37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('equipments', 'equipment_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise', 'exercise_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise', 'visible_for',
               existing_type=postgresql.ENUM('only_myself', 'staff_of_my_club', 'members_of_my_club', 'everyone_in_my_club', name='visiblefor'),
               nullable=True)
    op.alter_column('exercise', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercise', 'exercise_intensity',
               existing_type=postgresql.ENUM('irm', 'max_intensity', name='intensity'),
               nullable=True)
    op.alter_column('exercise', 'exercise_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise', 'difficulty',
               existing_type=postgresql.ENUM('Novice', 'Beginner', 'Intermediate', 'Advance', 'Expert', name='difficulty'),
               nullable=True)
    op.alter_column('exercise_category', 'category_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('met', 'met_value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('muscle', 'muscle_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('primary_joint', 'joint_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('primary_joint', 'joint_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('muscle', 'muscle_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('met', 'met_value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise_category', 'category_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise', 'difficulty',
               existing_type=postgresql.ENUM('Novice', 'Beginner', 'Intermediate', 'Advance', 'Expert', name='difficulty'),
               nullable=False)
    op.alter_column('exercise', 'exercise_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise', 'exercise_intensity',
               existing_type=postgresql.ENUM('irm', 'max_intensity', name='intensity'),
               nullable=False)
    op.alter_column('exercise', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercise', 'visible_for',
               existing_type=postgresql.ENUM('only_myself', 'staff_of_my_club', 'members_of_my_club', 'everyone_in_my_club', name='visiblefor'),
               nullable=False)
    op.alter_column('exercise', 'exercise_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('equipments', 'equipment_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
